# This file was generated by GoReleaser. DO NOT EDIT.
cask "mf" do
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/jlavera/mf-cli/releases/download/v#{version}/mf_darwin_amd64.tar.gz"
      sha256 "267432292a5c5c86c05927ccb8ad847d11b4f93386e8667d4360fe09085a51c0"
    end
    on_arm do
      url "https://github.com/jlavera/mf-cli/releases/download/v#{version}/mf_darwin_arm64.tar.gz"
      sha256 "0c328fa6dc1dc71d72c21d1bfc56f63a6ce2f89275d5ea5903f284f2bd23381e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jlavera/mf-cli/releases/download/v#{version}/mf_linux_amd64.tar.gz"
      sha256 "d9b038f0576c068f3b2f37fa3f22dcfc2e785ebd846fe4b4603fd993d890210a"
    end
    on_arm do
      url "https://github.com/jlavera/mf-cli/releases/download/v#{version}/mf_linux_arm64.tar.gz"
      sha256 "0497d104cb465b2671a1007cefd72f63a833ee7f1ce8dc478f3d8b9b18743520"
    end
  end

  name "mf"
  desc "CLI tool that wraps docker-compose for project management"
  homepage "https://github.com/jlavera/mf-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mf"]
    end
  end

  # No zap stanza required

end
