# This file was generated by GoReleaser. DO NOT EDIT.
cask "mf" do
  version "1.0.7"

  on_macos do
    on_intel do
      sha256 "28bd0876616b8648bbf1d10d3845c4d863c6c140c1e2dbef979aa31c62a386a1"
      url "https://github.com/jlavera/mf-cli/releases/download/v#{version}/mf_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "57e6a2d4b24c3077bf2fd768ec6e4029a41d6a3e079a7c8be093bd35fd49ef1a"
      url "https://github.com/jlavera/mf-cli/releases/download/v#{version}/mf_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b149986635a3d1e18571ed56f019d5d4bb754a0d276371c858b9d16beedaebe4"
      url "https://github.com/jlavera/mf-cli/releases/download/v#{version}/mf_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "173f295321558cb1cdd84ac950429b39fb3343c606d040d223541e7092d3dc5f"
      url "https://github.com/jlavera/mf-cli/releases/download/v#{version}/mf_linux_arm64.tar.gz"
    end
  end

  name "mf"
  desc "CLI tool that wraps docker-compose for project management"
  homepage "https://github.com/jlavera/mf-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mf"]
    end
  end

  # No zap stanza required

end
