# This file was generated by GoReleaser. DO NOT EDIT.
cask "mf" do
  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "9018645c17ed686090838681c7dce531c34bbd299f18a4ed5c2f682437a992fd"
      url "https://github.com/jlavera/mf-cli/releases/download/v#{version}/mf_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f0446afb30cc4cd021d20be54b9202c724cdb00eb7bba2dec1996689ad0b5d34"
      url "https://github.com/jlavera/mf-cli/releases/download/v#{version}/mf_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2f277d7e5e5be7c87214771720ab35485a1a1a997f5d3a8569d48ae15950ebec"
      url "https://github.com/jlavera/mf-cli/releases/download/v#{version}/mf_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e87bd385dc8328eb119452ebd64b2411a34f876e6e16e2d9b1f97491ae73b889"
      url "https://github.com/jlavera/mf-cli/releases/download/v#{version}/mf_linux_arm64.tar.gz"
    end
  end

  name "mf"
  desc "CLI tool that wraps docker-compose for project management"
  homepage "https://github.com/jlavera/mf-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mf"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mf"]
    end
  end

  # No zap stanza required

end
